version: '3'
services:
   webserver:
      build: ./
      container_name: webserver
      ports:
        - "8080:80"
      restart: unless-stoped
   mariadb:
     image: mariadb 
     restart:unless-stoped
     container_name: mariadb

   phpmyadmin:
      image: 
      container_name: phpmyadmin
      restart: unless-stoped
      ports: '8081:80'
     
