version: '3'
services:
   ubuntu:
      container_name: webserver${NAME_PREFIX}
      stdin_open: true
      tty: true
      build: ./
      ports:
        - '${APACHE2_HTTP_PORT}:80'
        - '${SSH_PORT}:22'
      restart:  always
      links:
        - 'mysql'
      volumes:
        - '${SITE_VOLUME}:/var/www/injdor.ru'
        - '${SITE2_VOLUME}:/var/www/volodin73.ru'
   mysql:
      image: mysql:latest 
      restart: always
      container_name: mysql${NEW_PREFIX}
      stdin_open: true
      tty: true
      environment:
         MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
         MYSQL_DATABASE: '${MYSQL_DATABASE}'
         MYSQL_USER: '${MYSQL_USER}'
         MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
         MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD}'
#      command: 'mysqld --initialize --user=mysql --basedir=/usr --datadir=/var/lib/mysql'
      ports: 
        - '${MYSQL_PORT}:3306'
      volumes:
         - '${MYSQL_VOLUME}:/var/lib/mysql'
         - './dump/injdor_dump.sql:/docker-entrypoint-initdb.d/injdor_dump.sql'
   
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin${NAME_PREFIX}
      restart: always
      ports: 
        - '${PHPMYADMIN_PORT}:80'
      environment:
         PMA_HOST: mysql
         MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
         UPLOAD_LIMIT: 3000000000
#        PMA_USER: '$PMA_USER'
#         PMA_PASSWORD: '$PMA_PASSWORD'
      depends_on: 
        - 'mysql'
      links:
        - 'mysql'
